apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: portainer-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portainer-demo
  template:
    metadata:
      labels:
        app: portainer-demo
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
