apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: portainer-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portainer-demo
  template:
    metadata:
      labels:
        app: portainer-demo
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: portainer-demo-service
spec:
  type: NodePort
  selector:
    app: portainer-demo
  ports:
  - nodePort: 30080
    port: 80
    targetPort: 80
